export const SET_SNACK_SUCCESS = 'SET_SNACK_SUCCESS';
export const SET_SNACK_ERROR = 'SET_SNACK_ERROR';
export const SET_SNACK_WARNING = 'SET_SNACK_WARNING';
export const SET_SNACK_CLOSE = 'SET_SNACK_CLOSE';